# Site settings
title: tamara ramudo
email: tamara.trt@gmail.com
url: https://tamarart.github.io/portfolio
description: "Tamara Ramudo Portfolio. A Barcelona based digital Designer"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
 primary: 39CCCC #39CCCC
 secondary: F0F0F0 #F0F0F0
 secondary-dark: 333333 #333

# Footer settings
footer:
  copyright: yo misma
  location: Location
  social: Around the Web
  made: Made with Bootstrap and Jekyll. Starting from the theme Freelancer.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: google-plus
    url: http://google.com/+TamaraRamudo
  - title: linkedin
    url: https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile
  - title: github
    url: https://github.com/tamarart
  - title: behance
    url: https://www.behance.net/tamararamudo

# Postal address (add as many lines as necessary)
address:
  - line: Barcelona

# Credits content
credits: '<a href="></a>'

# Build settings
markdown: kramdown
permalink: pretty
